id: I65A70865
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:45:51+00:00'
last_modified: '2022-06-07T21:20:58.410315+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16781
  title: མཚན་ཉིད་གསུམ་གྱི་རྣམ་གཞག་ག་པུར་ཐིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5E55:
      image_group_id: I8LS16792
      title: ''
      total_pages: 43
      order: 1
      base_file: 5E55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
