id: P004242
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS16781
  title: མཚན་ཉིད་གསུམ་གྱི་རྣམ་གཞག་ག་པུར་ཐིགས་པ།
  author: ''
  volumes:
    03ac3e8bc0be4d93b36e18bed89ca695:
      image_group_id: I8LS16792
      title: ''
      volume_number: 1
      total_pages: 43
      base_file: v001.txt
